version: "3.9"
services:
  db:
    container_name: pg_container
    image: postgres:14.2
    environment: 
      POSTGRES_DB: culvers_flavor_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - '5436:5432'
    restart: always

  pgadmin:
    container_name: pgadmin4_container 
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
    - "5050:80"
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdb:
    driver: local
  pgadmin:
    driver: local

